version: "3"

networks:
  web-file-transfer:

services:
  frontend:
    container_name: frontend
    build: ./frontend-wft
    environment:
      PORT: 8081
      REACT_APP_BACKEND_URL: http://${BACKEND_IP}:8080
    networks:
      - web-file-transfer
    ports:
      - "8081:8081"
  
  backend:
    container_name: backend
    build: ./backend-wft
    environment:
      - ALLOWED_ORIGINS=["${BACKEND_IP}"]
      - BASE_URL=http://${BACKEND_IP}:8080/
      - DATA_DIR=/home/data/
      - UPLOAD_DIR=/home/data/uploadDir/
      - UPLOAD_FILE_DURATION=60000
    networks:
      - web-file-transfer
    ports:
      - "8080:8080"
    volumes:
      - 'webfiletransfer_data:/home/data'
